/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bao.w.VIEW;

import com.mycompany.bao.w.CategoriaDAO;
import com.mycompany.bao.w.DTO.Categoria;
import com.mycompany.bao.w.DTO.EditoraEstudio;
import com.mycompany.bao.w.DTO.Escritor;
import com.mycompany.bao.w.DTO.Universal;
import com.mycompany.bao.w.EditoraEstudioDAO;
import com.mycompany.bao.w.EscritorDAO;
import com.mycompany.bao.w.UniversalDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author vrnm
 */
public class CadastroUniversal extends javax.swing.JFrame {

    

    /**
     * Creates new form CadastroUniversal
     */
    public CadastroUniversal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoid = new javax.swing.ButtonGroup();
        tipoEdes = new javax.swing.ButtonGroup();
        sexo = new javax.swing.ButtonGroup();
        status = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        textSinopse = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        int1 = new javax.swing.JRadioButton();
        int2 = new javax.swing.JRadioButton();
        int3 = new javax.swing.JRadioButton();
        textNome = new javax.swing.JTextField();
        textCapitulo = new javax.swing.JTextField();
        textTituloAl = new javax.swing.JTextField();
        textNomeEdes = new javax.swing.JTextField();
        intEd = new javax.swing.JRadioButton();
        intEs = new javax.swing.JRadioButton();
        textEscritor = new javax.swing.JTextField();
        Fe = new javax.swing.JRadioButton();
        Ma = new javax.swing.JRadioButton();
        Outros = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        textLink = new javax.swing.JTextField();
        textCategoria = new javax.swing.JTextField();
        bntCadastraUniversal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        novaCategoria = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        textSinopset = new javax.swing.JTextArea();
        bntCriacategoria = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        textSinopse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSinopseActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipoid.add(int1);
        int1.setText("1 - Anime");

        tipoid.add(int2);
        int2.setText("2 - Mangá");

        tipoid.add(int3);
        int3.setText("3 - Novel");

        tipoEdes.add(intEd);
        intEd.setText("Editora");

        tipoEdes.add(intEs);
        intEs.setText("Estudio");

        textEscritor.setText("Nome do Escritor");
        textEscritor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEscritorActionPerformed(evt);
            }
        });

        sexo.add(Fe);
        Fe.setText("Feminino");

        sexo.add(Ma);
        Ma.setText("Masculino");

        sexo.add(Outros);
        Outros.setText("Outros");

        jLabel1.setText("Genero:");

        bntCadastraUniversal.setText("Cadastrar");
        bntCadastraUniversal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastraUniversalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Cadastro Universal");
        jLabel2.setToolTipText("");

        jLabel3.setText("Status:");

        status.add(jRadioButton1);
        jRadioButton1.setText("Concluido");

        status.add(jRadioButton2);
        jRadioButton2.setText("Incompleto");

        status.add(jRadioButton3);
        jRadioButton3.setText("Andamento");

        status.add(jRadioButton4);
        jRadioButton4.setText("Desistiu");

        jLabel4.setText("Nome:");

        jLabel5.setText("Capitulos:");

        jLabel6.setText("Sinopse:");

        jLabel7.setText("Titulo Alternativo:");

        jLabel8.setText("Nome Editora/Estudio:");

        jLabel9.setText("Nome do Escritor:");

        jLabel10.setText("Link:");

        jLabel11.setText("Categoria:");

        jLabel12.setText("Nova Categoria:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romance", "Fantasia", "Terror", "Aventura" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        textSinopset.setColumns(20);
        textSinopset.setRows(5);
        jScrollPane2.setViewportView(textSinopset);

        bntCriacategoria.setText("Criar");
        bntCriacategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCriacategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(bntCadastraUniversal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel10))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textLink, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195))
                            .addComponent(textTituloAl, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNomeEdes, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(intEd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intEs))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Outros))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(novaCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntCriacategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(41, 41, 41))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(int3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(int1)
                                            .addComponent(int2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(int1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(int2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(int3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTituloAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNomeEdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intEd)
                    .addComponent(intEs))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Fe)
                    .addComponent(Ma)
                    .addComponent(Outros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(novaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCriacategoria))
                .addGap(18, 18, 18)
                .addComponent(bntCadastraUniversal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textEscritorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEscritorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEscritorActionPerformed

    private void bntCadastraUniversalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastraUniversalActionPerformed
        String nome, sinopse, tipo ,tituloal, nomeEdes, nomeEsc, link, cat, capitulo, tiEdes, genero, sta;
        
        nome = textNome.getText();
        sinopse = textSinopset.getText();
        tipo = tipoid.getSelection().toString();
        tituloal = textTituloAl.getText();
        nomeEdes = textNomeEdes.getText();
        tiEdes = tipoEdes.getSelection().toString();
        nomeEsc = textEscritor.getText();
        genero = sexo.getSelection().toString();
        sta = status.getSelection().toString();
        link = textLink.getText();
        cat = textCategoria.getText();
        capitulo = textCapitulo.getText();
        
        JOptionPane.showMessageDialog(rootPane, tipoid.getSelection());
        JOptionPane.showMessageDialog(rootPane, tipoEdes.getSelection());
        JOptionPane.showMessageDialog(rootPane, sexo.getSelection());
        JOptionPane.showMessageDialog(rootPane, status.getSelection());
        
        Categoria categoria = new Categoria();
        categoria.setNome(cat);
        
        CategoriaDAO categoriadao = new CategoriaDAO();
        categoriadao.CadastrarCategoria(categoria);
        
        Universal universal = new Universal();
        universal.setNome(nome);
        universal.setSinopse(sinopse);
        universal.setTipo(tipo);
        universal.setCapitulos(capitulo);
        universal.setStatus(sta);
        universal.setNome_alternativo(tituloal);
        universal.setLink(link);
        
        UniversalDAO universaldao = new UniversalDAO();
        universaldao.CadastrarUniversal(universal);
        
        EditoraEstudio edes = new EditoraEstudio();
        edes.setNome(nomeEdes);
        edes.setTipo(tipo);
        
        EditoraEstudioDAO eddao = new EditoraEstudioDAO();
        eddao.CadastrarEditoraEstudio(edes);
        
        Escritor esc = new Escritor();
        esc.setNome(nomeEsc);
        esc.setSexo(genero);
        
        
        EscritorDAO escritordao = new EscritorDAO();
        escritordao.CadastrarEscritor(esc);
        
    }//GEN-LAST:event_bntCadastraUniversalActionPerformed

    private void textSinopseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSinopseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSinopseActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
            String categoriaSelecionada = jComboBox2.getSelectedItem().toString();
            textCategoria.setText(categoriaSelecionada);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void bntCriacategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCriacategoriaActionPerformed
        String cat = novaCategoria.getText();
        jComboBox2.addItem(cat);
        novaCategoria.setText("");
    }//GEN-LAST:event_bntCriacategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUniversal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUniversal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUniversal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUniversal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUniversal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Fe;
    private javax.swing.JRadioButton Ma;
    private javax.swing.JRadioButton Outros;
    private javax.swing.JButton bntCadastraUniversal;
    private javax.swing.JButton bntCriacategoria;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton int1;
    private javax.swing.JRadioButton int2;
    private javax.swing.JRadioButton int3;
    private javax.swing.JRadioButton intEd;
    private javax.swing.JRadioButton intEs;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField novaCategoria;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.ButtonGroup status;
    private javax.swing.JTextField textCapitulo;
    private javax.swing.JTextField textCategoria;
    private javax.swing.JTextField textEscritor;
    private javax.swing.JTextField textLink;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNomeEdes;
    private javax.swing.JTextField textSinopse;
    private javax.swing.JTextArea textSinopset;
    private javax.swing.JTextField textTituloAl;
    private javax.swing.ButtonGroup tipoEdes;
    private javax.swing.ButtonGroup tipoid;
    // End of variables declaration//GEN-END:variables

    void setVision(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
